INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목 1', '내용 1', 'user1', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목 2', '내용 2', 'user2', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목 3', '내용 3', 'user3', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목 4', '내용 4', 'user4', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목 5', '내용 5', 'user5', NOW(), NOW())